### ISSUE TITLE
Waypoint and Teleport Books don't display correctly when resolving user is not OP

### ISSUE THREAD

**Issue by leonx132** [Fisch37/waypoints-vanilla#2] opened 2024-01-21 22:03 UTC
i have luckperms set up with essential commands is there some kind of permissions i need to enable for default users

**Comment by leonx132** [comment] 2024-01-21 22:04
![image](https://github.com/Fisch37/waypoints-vanilla/assets/37477094/87f38dd5-ddf7-40ff-9fdc-050d9a46c61b)

this is what the book looks like when they try to sign the way point book

**Comment by PascalRombach** [comment] 2024-01-22 06:30
There should not be any required permission for crafting a waypoint book, but what you have looks quite like a bug.

You say you have Luckperms installed, are there any other mods/plugins I should be aware of? On first glance this looks like an AntiCheat issue

**Comment by Fisch37** [comment] 2024-01-22 06:36
At first glance this looks like it could be a conflict with AntiCheat systems. Are there any other mods/plugins you have installed? What server loader are you running?

**Comment by leonx132** [comment] 2024-01-22 15:12
Cross-Play
-Geyser-FabricMC[The mod that enables Crossplay]
-Floodgate[Helps with net code from bedrock players]

Admin & Anti Cheat;
-Anti Xray
-Illegal Stack Fixer[Resets stack count to maximum stack size]
-Inv View[Allows you to open and manipulate the inventories and ender chests of online and offline players. Server Side]
-LuckPerms[A permissions plugin (mod) for Minecraft servers]
-Secret Spectator[hides spectator mode from the player list for other non-spectator players]
-worldedit
-luck perms



API's, Lib's & Librarys required for other mods;
-Architectury API[APIs are Required by certan mods to help them load] 
-Fabric API[mandatory for the server to run fabric mods]
-Cloth Config API[API used by most everything]
-Collective[Collective is a shared library with common code for all of Serilum's mods]
-Cristel Lib[A Library mod for easy structure config and runtime datapacks]
-Fabric Language Kotlin[enables usage of the Kotlin programming language for Fabric mods]
-MidnightLib[Common library with a built-in configuration system]
-VillagerConfig[Advanced Villager configuration with data driven trades]
-luck perms fabric place holder API


Server performance;
-Concurrent Chunk Management Engine[improves the performance of chunk generation, I/O, and loading]
-FerriteCore[Memory usage optimizations]
-Krypton[optimizes the Minecraft networking stack]
-Lithium[improve a number of systems (game physics, mob AI, block ticking, etc) with the goal of not changing any vanilla mechanics]
-Memory Leak Fix[fixes random memory leaks for both the client and server]
-MixinTrace[Adds a list of mixins in the stack trace to crash reports]
-ModernFix[All-in-one mod that improves performance, reduces memory usage, and fixes many bugs.]
-Starlight[Rewrites the light engine to fix lighting performance and lighting errors]



QoL
-Better Spawner Control[Disables mob spawners whenever they are surrounded by 5 torches]
-CalcMod[A calculator in your chat with shortcuts designed for Minecraft, /calc <expression>]
-Crying Portals[Allows the creation of nether portals with crying obsidian blocks]
-Cycle Paintings[Easily cycle through placed paintings by right-clicking them with another painting in hand]
-Dimensional Tracker[Color names depending on the player's dimension]
-Double Doors[Multiple identical double doors, trapdoors and fence gates can be opened simultaneously]
-Egg Of Capitalism[OUR ender dragon egg, Get a dragon egg for every "The End." achievement]
-EnchantedShulkers[adds the "Siphon" and "Refill" enchantments to the game]
-Fast RTP[A fast random teleport command that doesn't cause lagspikes, /rtp, /rtpback]
-Get It Together, Drops![Increases the size of the area in which a dropped item will search for other dropped items to combine with]
-Glowing Ores[adds light emission to ores]
-Glowing Torchflower[makes Torchflower glow]
-Healing Campfire[Creates an area around the (soul) campfire where players and passive mobs receive regeneration]
-Horse Buff[QOL tweaks for horses]
-JourneyMap[Real-time mapping in game or in a web browser as you explore]
-Mine Spawners[mine spawners using a pickaxe with silk touch]
-Monsters in the Closet[Highlights the mobs that are preventing you from sleeping]
-Netherite Beacons[Netherite blocks in the beacon base make the primary effect 1 level higher for every 2 netherite blocks added. Haste is the only exception to this, and it will increase by 1 level per netherite block]
-Quick Paths[Create long paths instantly by setting a start and end point, Crouch + right-click a block with a shovel to set the starting point. Right click any other block with the shovel to finish the path]
-Recast[Automatically re-casts the fishing rod line for a player when an item is caught]
-Server Sleep[Changes playersSleepingPercentage to 50%]
-Simple Quests[server sided questing mod]
-Slime[/slime command to find slime chunks]
-Starter Kit[Gives players joining the world for the first time a kit]
-Custom Biome Saplings[Allows Terralith and Blooming Biosphere trees to be regrown using vanilla saplings]
-Wandering Slave Trader[Enables 0-2 villager spawn eggs to be bought from Wandering Traders]
-Sessility[Hide AFK players in tab list, exclude AFK players from the sleeping requirement]
-followers teleport too
-

Economic & Player utility Mods
-Diamond Economy[Simple diamond-based economy, /diamonds]
-Diamond Chest Shops[Create buy or sell shops in chests or barrels with signs. Click with a command block to make an admin shop /diamonds chestshops]
-Diamond Auction House[Auction House Addon for Diamond Economy]
-Get Off My Lawn ReServed[Keep people off your lawn with claims]
-Hey That's Mine[container claiming and trusting system]
-Waypoints[Brings waypoints to Vanilla Minecraft]
-your items are safe[gravestone like mod]


Mob Changes;
-Cave Spider Spawn[Adds a chance for cave spiders to spawn naturally underground instead of a spider]
-Giant Spawn[Allows giants to spawn naturally with custom AI]
-Husk Spawn[Adds a chance for husks to spawn naturally everywhere in place of a zombie]
-Mob Captains[Rare and strong mobs will spawn, dropping illegally enchanted gear]
-Naturally Charged Creepers[Allows creepers to spawn charged]
-Skeleton Horse Spawn[Allows skeleton horses to spawn naturally with a skeleton riding it and other tweaks]
-True Ending: Ender Dragon Overhaul[A dramatic overhaul to the Ender Dragon boss fight]
-Upgraded Mobs[Adds new attacks and abilities to a variety of mobs]
-Wither Skeleton Archers in Fortresses[Replaces skeletons in fortresses with bow-wielding wither skeletons]
-Zombie Horse Spawn[Allows zombie horses to spawn with a zombie riding it and other tweaks]



Structures;
-AdoraBuild: Structures[adds 85 new structures]
-Dungeons and Taverns[adds 21 new structures]
-Repurposed Structures[adds 100+ new structures]
-Additional Structures[Adds >200 new structures]
-Towns and Towers[Adds over 50 structures]
-Vanilla Sky Villages[add Vanilla Sky Villages]
-



Biomes;
-Profundis: Seven New Quality Cave Biomes[A world generation mod adding in seven new underground biomes]
-Terralith[adds over 95 brand new biomes, as well as updating almost every vanilla biome with new and improved features]
-



Misc;
-First Join Message[Sends players who join a world for the first time a configurable message]
-Flat Bedrock[Make the world have flat bedrock]
-Just Mob Heads[Adds a chance for mobs to drop their head, looting dosent chage drop rates, only charged creepers drop creeper heads]
-Just Player Heads[Allows the collection of player heads, 50% Chance on death]
-ItemFlexer[allows you to flex you items, /flex] 
-Random Shulker Colours[Gives new shulker spawns a random shell color based on a configurable list]
-Random Sheep Colours[Gives new sheep spawns a random wool/fleece color]
-Villager Names[Gives all villager entities a default or custom name to liven up the world]
-Styled Player List[allows server owners to change player list look]
-styled chat

Discord;
-Fabric to Discord
-MC discord chat

**Comment by leonx132** [comment] 2024-01-22 15:15
idk why some of it is bold but this is everything i use on my server

**Comment by Fisch37** [comment] 2024-01-22 19:10
That's... quite a lot. I don't have the time to check that right now, but I'll do some testing soon.
In the meantime: I assume all of your mods are up-to-date? Have you tried strategically disabling certain mods and test if it works?

**Comment by leonx132** [comment] 2024-01-22 19:31
yes all my mods are up to date, is there any way to find out what mod is causing the issue other than remove them one by one till it works?

**Comment by Fisch37** [comment] 2024-01-22 19:33
Well if you have some sort of error or warning that occurs in log when you try to create a waypoint, that would be ideal. (I honestly doubt it though)

**Comment by leonx132** [comment] 2024-01-22 20:39
theres nothing sorry 

but i just finished testing all my mods, removed them all one by one till i was only left with yours 

turns out its a config not the mod thats causing the conflict, so im going to now add my mods back a small amount at a time so they can generate new configs untill i can narrow down what is causing the issue

**Comment by leonx132** [comment] 2024-01-22 20:45
ok so ive removed every single mod and config i only have your mod, cloth config and fabric API 

and still only an OP can sign the waypoint book with out any issues

**Comment by leonx132** [comment] 2024-01-22 20:51
![image](https://github.com/Fisch37/waypoints-vanilla/assets/37477094/b51b6353-b686-4fdd-8ccf-7ac1a9992012)
none operators get this still 

![image](https://github.com/Fisch37/waypoints-vanilla/assets/37477094/27647393-1867-42b0-a9fe-ef8380f0021f)
works fine when im op'ed

**Comment by Fisch37** [comment] 2024-01-22 20:53
Oh! Well that's much more testable!

**Comment by leonx132** [comment] 2024-01-22 20:56
do you have permissions for this mod that would make it so only an OP can sign it and it works

**Comment by Fisch37** [comment] 2024-01-22 20:58
I haven't set any values like that, if that's what you mean. This is solidly a bug

**Comment by leonx132** [comment] 2024-01-22 21:00
well shit XD least i can craft it for other players for now, hopfully u can find a fix soonish

GL thou

**Comment by Fisch37** [comment] 2024-01-22 21:01
It'll definitely be an interesting journey, thanks for the notice!

**Comment by Fisch37** [comment] 2024-01-23 19:56
Update: I have managed to reproduce this bug

**Comment by Fisch37** [comment] 2024-01-23 20:00
Bug also occurs when adding a new waypoint to the teleport book.
Almost guaranteed: Data resolution requires OP permissions (for some reason)

**Comment by Fisch37** [comment] 2024-01-23 20:04
Update: This is a known bug with Minecraft ([MC-103171](https://bugs.mojang.com/browse/MC-103171))

**Comment by Fisch37** [comment] 2024-01-23 20:11
vdvman1 suggests pre-resolving text components using text displays or signs. (The selector system doesn't work in this case though. He recommends saving data into storage temporarily)

This will significantly complicate book generation, but it can be done (and so it will be)

**Comment by Fisch37** [comment] 2024-01-23 21:25
The latest state on github should fix the issue with Waypoint Books. Teleport Books will still not work though

**Comment by leonx132** [comment] 2024-01-23 22:18
so can users sign the book? 

what do you mean by "Teleport Books will still not work though"

**Comment by Fisch37** [comment] 2024-01-24 18:14
The version you have right now won't fix the issue. I'm still working on a complete fix which may take until the end of the week to reach a release.
If it's urgent, you can download the code from Github directly, but once more: The latest commit does not completely solve the problem. Rather, when you create a new waypoint the issue is fixed. Non-OP users adding pages to their teleport books (the ones you craft with 8 Echo Shards) will still see broken pages. (Unreleased code has an increased risk of breaking so beware)

I should add however, that the data for the books is unaffected so there's no danger to your existing waypoints. In theory you could even use `/trigger goto_waypoint_rel set <page_number>` to teleport provided you hold the book in your hand while doing so. (e. g. `/trigger goto_waypoint_rel set 1` to teleport to the waypoint that would be shown on page 1)

**Closed as completed** 2024-01-25 14:15 UTC
Labels: bug, Prio: HIGH

**Comment by Fisch37** [comment] 2024-02-01 19:52
The new version is now released on modrinth and github.
